#############################################################################
# Makefile for building: SSniffer
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  SSniffer.pro
# Template: app
# Command: /usr/local/Qt-5.3.2/bin/qmake -spec linux-g++ -o Makefile SSniffer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/local/Qt-5.3.2/mkspecs/linux-g++ -I. -isystem /usr/include -I/usr/local/Qt-5.3.2/include -I/usr/local/Qt-5.3.2/include/QtWidgets -I/usr/local/Qt-5.3.2/include/QtGui -I/usr/local/Qt-5.3.2/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Qt-5.3.2/lib
LIBS          = $(SUBLIBS) -L /usr/lib/x86_64-linux-gnu -lpcap -L/usr/local/Qt-5.3.2/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Qt-5.3.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dialog.cpp \
		snifferthread.cpp moc_dialog.cpp \
		moc_snifferthread.cpp
OBJECTS       = main.o \
		dialog.o \
		snifferthread.o \
		moc_dialog.o \
		moc_snifferthread.o
DIST          = /usr/local/Qt-5.3.2/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.3.2/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/unix.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/linux.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.3.2/mkspecs/qconfig.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.3.2/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.3.2/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/qt.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/resources.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/moc.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/uic.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/lex.prf \
		SSniffer.pro main.cpp \
		dialog.cpp \
		snifferthread.cpp
QMAKE_TARGET  = SSniffer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SSniffer


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SSniffer.pro /usr/local/Qt-5.3.2/mkspecs/linux-g++/qmake.conf /usr/local/Qt-5.3.2/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.3.2/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/unix.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/linux.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.3.2/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.3.2/mkspecs/qconfig.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.3.2/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.3.2/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.3.2/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/qt.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/resources.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/moc.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/uic.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.3.2/mkspecs/features/lex.prf \
		SSniffer.pro \
		/usr/local/Qt-5.3.2/lib/libQt5Widgets.prl \
		/usr/local/Qt-5.3.2/lib/libQt5Gui.prl \
		/usr/local/Qt-5.3.2/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile SSniffer.pro
/usr/local/Qt-5.3.2/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.3.2/mkspecs/common/shell-unix.conf:
/usr/local/Qt-5.3.2/mkspecs/common/unix.conf:
/usr/local/Qt-5.3.2/mkspecs/common/linux.conf:
/usr/local/Qt-5.3.2/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.3.2/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-5.3.2/mkspecs/common/g++-base.conf:
/usr/local/Qt-5.3.2/mkspecs/common/g++-unix.conf:
/usr/local/Qt-5.3.2/mkspecs/qconfig.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-5.3.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt-5.3.2/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.3.2/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.3.2/mkspecs/linux-g++/qmake.conf:
/usr/local/Qt-5.3.2/mkspecs/features/spec_post.prf:
/usr/local/Qt-5.3.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.3.2/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.3.2/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.3.2/mkspecs/features/default_post.prf:
/usr/local/Qt-5.3.2/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.3.2/mkspecs/features/qt.prf:
/usr/local/Qt-5.3.2/mkspecs/features/resources.prf:
/usr/local/Qt-5.3.2/mkspecs/features/moc.prf:
/usr/local/Qt-5.3.2/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.3.2/mkspecs/features/uic.prf:
/usr/local/Qt-5.3.2/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.3.2/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.3.2/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.3.2/mkspecs/features/yacc.prf:
/usr/local/Qt-5.3.2/mkspecs/features/lex.prf:
SSniffer.pro:
/usr/local/Qt-5.3.2/lib/libQt5Widgets.prl:
/usr/local/Qt-5.3.2/lib/libQt5Gui.prl:
/usr/local/Qt-5.3.2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile SSniffer.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/SSniffer1.0.0 || mkdir -p .tmp/SSniffer1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/SSniffer1.0.0/ && $(COPY_FILE) --parents dialog.h snifferthread.h .tmp/SSniffer1.0.0/ && $(COPY_FILE) --parents main.cpp dialog.cpp snifferthread.cpp .tmp/SSniffer1.0.0/ && $(COPY_FILE) --parents dialog.ui .tmp/SSniffer1.0.0/ && (cd `dirname .tmp/SSniffer1.0.0` && $(TAR) SSniffer1.0.0.tar SSniffer1.0.0 && $(COMPRESS) SSniffer1.0.0.tar) && $(MOVE) `dirname .tmp/SSniffer1.0.0`/SSniffer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SSniffer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_dialog.cpp moc_snifferthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_snifferthread.cpp
moc_dialog.cpp: snifferthread.h \
		/usr/local/Qt-5.3.2/include/QtCore/QThread \
		/usr/local/Qt-5.3.2/include/QtCore/qthread.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.3.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.3.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.3.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.3.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.3.2/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmutex.h \
		/usr/local/Qt-5.3.2/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.3.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.3.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.3.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.3.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.3.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.3.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.3.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.3.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.3.2/include/QtCore/QStringList \
		/usr/local/Qt-5.3.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.3.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.3.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.3.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.3.2/include/QtCore/QMap \
		/usr/local/Qt-5.3.2/include/QtCore/qmap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qdebug.h \
		/usr/local/Qt-5.3.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlocale.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvariant.h \
		/usr/local/Qt-5.3.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.3.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.3.2/include/QtCore/qset.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.3.2/include/QtCore/QMutex \
		/usr/local/Qt-5.3.2/include/QtWidgets/QDialog \
		/usr/local/Qt-5.3.2/include/QtWidgets/qdialog.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.3.2/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.3.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmargins.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/qrect.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsize.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpalette.h \
		/usr/local/Qt-5.3.2/include/QtGui/qcolor.h \
		/usr/local/Qt-5.3.2/include/QtGui/qrgb.h \
		/usr/local/Qt-5.3.2/include/QtGui/qbrush.h \
		/usr/local/Qt-5.3.2/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.3.2/include/QtGui/qregion.h \
		/usr/local/Qt-5.3.2/include/QtCore/qline.h \
		/usr/local/Qt-5.3.2/include/QtGui/qtransform.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.3.2/include/QtGui/qimage.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.3.2/include/QtGui/qfont.h \
		/usr/local/Qt-5.3.2/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.3.2/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.3.2/include/QtGui/qcursor.h \
		/usr/local/Qt-5.3.2/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.3.2/include/QtGui/qevent.h \
		/usr/local/Qt-5.3.2/include/QtCore/qurl.h \
		/usr/local/Qt-5.3.2/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfile.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.3.2/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.3.2/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/QQueue \
		/usr/local/Qt-5.3.2/include/QtCore/qqueue.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QTreeWidgetItem \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtreewidget.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtreeview.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractitemview.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qframe.h \
		/usr/local/Qt-5.3.2/include/QtCore/qabstractitemmodel.h \
		/usr/local/Qt-5.3.2/include/QtCore/qitemselectionmodel.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qstyleoption.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractspinbox.h \
		/usr/local/Qt-5.3.2/include/QtGui/qvalidator.h \
		/usr/local/Qt-5.3.2/include/QtCore/qregularexpression.h \
		/usr/local/Qt-5.3.2/include/QtGui/qicon.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qslider.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractslider.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qstyle.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtabbar.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qrubberband.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtreewidgetitemiterator.h \
		dialog.h
	/usr/local/Qt-5.3.2/bin/moc $(DEFINES) -I/usr/local/Qt-5.3.2/mkspecs/linux-g++ -I/home/viczzx/workspace/Projects/QT/SSniffer -I/usr/include -I/usr/local/Qt-5.3.2/include -I/usr/local/Qt-5.3.2/include/QtWidgets -I/usr/local/Qt-5.3.2/include/QtGui -I/usr/local/Qt-5.3.2/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dialog.h -o moc_dialog.cpp

moc_snifferthread.cpp: /usr/local/Qt-5.3.2/include/QtCore/QThread \
		/usr/local/Qt-5.3.2/include/QtCore/qthread.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.3.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.3.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.3.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.3.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.3.2/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmutex.h \
		/usr/local/Qt-5.3.2/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.3.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.3.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.3.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.3.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.3.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.3.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.3.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.3.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.3.2/include/QtCore/QStringList \
		/usr/local/Qt-5.3.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.3.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.3.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.3.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.3.2/include/QtCore/QMap \
		/usr/local/Qt-5.3.2/include/QtCore/qmap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qdebug.h \
		/usr/local/Qt-5.3.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlocale.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvariant.h \
		/usr/local/Qt-5.3.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.3.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.3.2/include/QtCore/qset.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.3.2/include/QtCore/QMutex \
		snifferthread.h
	/usr/local/Qt-5.3.2/bin/moc $(DEFINES) -I/usr/local/Qt-5.3.2/mkspecs/linux-g++ -I/home/viczzx/workspace/Projects/QT/SSniffer -I/usr/include -I/usr/local/Qt-5.3.2/include -I/usr/local/Qt-5.3.2/include/QtWidgets -I/usr/local/Qt-5.3.2/include/QtGui -I/usr/local/Qt-5.3.2/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include snifferthread.h -o moc_snifferthread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h
ui_dialog.h: dialog.ui
	/usr/local/Qt-5.3.2/bin/uic dialog.ui -o ui_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp dialog.h \
		snifferthread.h \
		/usr/local/Qt-5.3.2/include/QtCore/QThread \
		/usr/local/Qt-5.3.2/include/QtCore/qthread.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.3.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.3.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.3.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.3.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.3.2/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmutex.h \
		/usr/local/Qt-5.3.2/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.3.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.3.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.3.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.3.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.3.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.3.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.3.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.3.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.3.2/include/QtCore/QStringList \
		/usr/local/Qt-5.3.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.3.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.3.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.3.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.3.2/include/QtCore/QMap \
		/usr/local/Qt-5.3.2/include/QtCore/qmap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qdebug.h \
		/usr/local/Qt-5.3.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlocale.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvariant.h \
		/usr/local/Qt-5.3.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.3.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.3.2/include/QtCore/qset.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.3.2/include/QtCore/QMutex \
		/usr/local/Qt-5.3.2/include/QtWidgets/QDialog \
		/usr/local/Qt-5.3.2/include/QtWidgets/qdialog.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.3.2/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.3.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmargins.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/qrect.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsize.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpalette.h \
		/usr/local/Qt-5.3.2/include/QtGui/qcolor.h \
		/usr/local/Qt-5.3.2/include/QtGui/qrgb.h \
		/usr/local/Qt-5.3.2/include/QtGui/qbrush.h \
		/usr/local/Qt-5.3.2/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.3.2/include/QtGui/qregion.h \
		/usr/local/Qt-5.3.2/include/QtCore/qline.h \
		/usr/local/Qt-5.3.2/include/QtGui/qtransform.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.3.2/include/QtGui/qimage.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.3.2/include/QtGui/qfont.h \
		/usr/local/Qt-5.3.2/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.3.2/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.3.2/include/QtGui/qcursor.h \
		/usr/local/Qt-5.3.2/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.3.2/include/QtGui/qevent.h \
		/usr/local/Qt-5.3.2/include/QtCore/qurl.h \
		/usr/local/Qt-5.3.2/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfile.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.3.2/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.3.2/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/QQueue \
		/usr/local/Qt-5.3.2/include/QtCore/qqueue.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QTreeWidgetItem \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtreewidget.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtreeview.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractitemview.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qframe.h \
		/usr/local/Qt-5.3.2/include/QtCore/qabstractitemmodel.h \
		/usr/local/Qt-5.3.2/include/QtCore/qitemselectionmodel.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qstyleoption.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractspinbox.h \
		/usr/local/Qt-5.3.2/include/QtGui/qvalidator.h \
		/usr/local/Qt-5.3.2/include/QtCore/qregularexpression.h \
		/usr/local/Qt-5.3.2/include/QtGui/qicon.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qslider.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractslider.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qstyle.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtabbar.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qrubberband.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtreewidgetitemiterator.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QApplication \
		/usr/local/Qt-5.3.2/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.3.2/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.3.2/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.3.2/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dialog.o: dialog.cpp dialog.h \
		snifferthread.h \
		/usr/local/Qt-5.3.2/include/QtCore/QThread \
		/usr/local/Qt-5.3.2/include/QtCore/qthread.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.3.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.3.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.3.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.3.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.3.2/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmutex.h \
		/usr/local/Qt-5.3.2/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.3.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.3.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.3.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.3.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.3.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.3.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.3.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.3.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.3.2/include/QtCore/QStringList \
		/usr/local/Qt-5.3.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.3.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.3.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.3.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.3.2/include/QtCore/QMap \
		/usr/local/Qt-5.3.2/include/QtCore/qmap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qdebug.h \
		/usr/local/Qt-5.3.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlocale.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvariant.h \
		/usr/local/Qt-5.3.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.3.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.3.2/include/QtCore/qset.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.3.2/include/QtCore/QMutex \
		/usr/local/Qt-5.3.2/include/QtWidgets/QDialog \
		/usr/local/Qt-5.3.2/include/QtWidgets/qdialog.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.3.2/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.3.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmargins.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/qrect.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsize.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpalette.h \
		/usr/local/Qt-5.3.2/include/QtGui/qcolor.h \
		/usr/local/Qt-5.3.2/include/QtGui/qrgb.h \
		/usr/local/Qt-5.3.2/include/QtGui/qbrush.h \
		/usr/local/Qt-5.3.2/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.3.2/include/QtGui/qregion.h \
		/usr/local/Qt-5.3.2/include/QtCore/qline.h \
		/usr/local/Qt-5.3.2/include/QtGui/qtransform.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.3.2/include/QtGui/qimage.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.3.2/include/QtGui/qfont.h \
		/usr/local/Qt-5.3.2/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.3.2/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.3.2/include/QtGui/qcursor.h \
		/usr/local/Qt-5.3.2/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.3.2/include/QtGui/qevent.h \
		/usr/local/Qt-5.3.2/include/QtCore/qurl.h \
		/usr/local/Qt-5.3.2/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfile.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.3.2/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.3.2/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/QQueue \
		/usr/local/Qt-5.3.2/include/QtCore/qqueue.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QTreeWidgetItem \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtreewidget.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtreeview.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractitemview.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qframe.h \
		/usr/local/Qt-5.3.2/include/QtCore/qabstractitemmodel.h \
		/usr/local/Qt-5.3.2/include/QtCore/qitemselectionmodel.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qstyleoption.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractspinbox.h \
		/usr/local/Qt-5.3.2/include/QtGui/qvalidator.h \
		/usr/local/Qt-5.3.2/include/QtCore/qregularexpression.h \
		/usr/local/Qt-5.3.2/include/QtGui/qicon.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qslider.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractslider.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qstyle.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtabbar.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qrubberband.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtreewidgetitemiterator.h \
		ui_dialog.h \
		/usr/local/Qt-5.3.2/include/QtCore/QVariant \
		/usr/local/Qt-5.3.2/include/QtWidgets/QAction \
		/usr/local/Qt-5.3.2/include/QtWidgets/qaction.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qactiongroup.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QApplication \
		/usr/local/Qt-5.3.2/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.3.2/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.3.2/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.3.2/include/QtGui/qinputmethod.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QButtonGroup \
		/usr/local/Qt-5.3.2/include/QtWidgets/qbuttongroup.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QHeaderView \
		/usr/local/Qt-5.3.2/include/QtWidgets/qheaderview.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QLabel \
		/usr/local/Qt-5.3.2/include/QtWidgets/qlabel.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QLineEdit \
		/usr/local/Qt-5.3.2/include/QtWidgets/qlineedit.h \
		/usr/local/Qt-5.3.2/include/QtGui/qtextcursor.h \
		/usr/local/Qt-5.3.2/include/QtGui/qtextformat.h \
		/usr/local/Qt-5.3.2/include/QtGui/qpen.h \
		/usr/local/Qt-5.3.2/include/QtGui/qtextoption.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QPushButton \
		/usr/local/Qt-5.3.2/include/QtWidgets/qpushbutton.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qabstractbutton.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QTextBrowser \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtextbrowser.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/qtextedit.h \
		/usr/local/Qt-5.3.2/include/QtGui/qtextdocument.h \
		/usr/local/Qt-5.3.2/include/QtWidgets/QTreeWidget \
		/usr/local/Qt-5.3.2/include/QtCore/QTime \
		/usr/local/Qt-5.3.2/include/QtCore/qdatetime.h \
		displaythread.h \
		/usr/local/Qt-5.3.2/include/QtCore/QDebug \
		/usr/local/Qt-5.3.2/include/QtCore/QByteArray
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

snifferthread.o: snifferthread.cpp snifferthread.h \
		/usr/local/Qt-5.3.2/include/QtCore/QThread \
		/usr/local/Qt-5.3.2/include/QtCore/qthread.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.3.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.3.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.3.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.3.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.3.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.3.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.3.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.3.2/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmutex.h \
		/usr/local/Qt-5.3.2/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.3.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.3.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.3.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.3.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.3.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.3.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.3.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.3.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.3.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.3.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.3.2/include/QtCore/QStringList \
		/usr/local/Qt-5.3.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.3.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.3.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.3.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.3.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.3.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.3.2/include/QtCore/QMap \
		/usr/local/Qt-5.3.2/include/QtCore/qmap.h \
		/usr/local/Qt-5.3.2/include/QtCore/qdebug.h \
		/usr/local/Qt-5.3.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.3.2/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.3.2/include/QtCore/qlocale.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvariant.h \
		/usr/local/Qt-5.3.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.3.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.3.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.3.2/include/QtCore/qset.h \
		/usr/local/Qt-5.3.2/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.3.2/include/QtCore/QMutex \
		/usr/local/Qt-5.3.2/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o snifferthread.o snifferthread.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_snifferthread.o: moc_snifferthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_snifferthread.o moc_snifferthread.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

